### ISSUE TITLE
jupyte notebook container  No space left on device: '/home/jovyan/.local'

### ISSUE THREAD

**Issue by baram204** [baram204/Used-Car-Price-Expectation-with-ML#4]
docker run -it --rm -p 8888:8888 jupyter/base-notebook

```
/usr/local/bin/start-notebook.sh: ignoring /usr/local/bin/start-notebook.d/*

Container must be run with group root to update passwd file
Container must be run as root to grant sudo permissions
Executing the command: jupyter notebook
[E 11:02:36.299 NotebookApp] Exception while loading config file /etc/jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/opt/conda/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/jupyter_notebook_config.py", line 20, in <module>
        os.makedirs(dir_name)
      File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
        makedirs(head, mode, exist_ok)
      File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
        makedirs(head, mode, exist_ok)
      File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    OSError: [Errno 28] No space left on device: '/home/jovyan/.local'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1505, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1209, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/home/jovyan/.local'
```

**Comment by baram204** [comment]
spend almost 6 hours.

first I focused below message :

```
Container must be run with group root to update passwd file
Container must be run as root to grant sudo permissions
```

and tried `docker run --user root [image]` but can't solve the issue.

search and try.. oh got tired.

I was meet this issue before. I do the same thing. and issues gone!

```
> docker system prune -a
WARNING! This will remove:
- all stopped containers
- all networks not used by at least one container
- all images without at least one container associated to them
- all build cache
Are you sure you want to continue? [y/N] y
......
> docker-compose up -d
```

https://zeewhon.blogspot.kr/2017/06/no-space-left-on-device.html

**Comment by baram204** [comment]
#6 관련 도커 이미지 빌드 시

ERROR: Service 'jupyter' failed to build: failed to register layer: Error processing tar file(exit status 1): write /usr/local/cuda-9.0/lib64/libnvgraph_static.a: no space left on device

**Comment by baram204** [comment]
It's lack of space on docker-machine's docker space..

```
```

fit backup downloaded images using save command
```
docker save -o ./mysql.tar mysql
docker save -o ./adminer.tar adminer
docker save -o ./jupyter-datascience-notebook.tar jupyter/datascience-notebook
docker save -o  ./flask.tar tiangolo/uwsgi-nginx-flask:python3.6
```


https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#running-out-of-space

**Comment by baram204** [comment]
fit backup downloaded images using save command.

```
docker save -o ./mysql.tar mysql
docker save -o ./adminer.tar adminer
docker save -o  ./flask.tar tiangolo/uwsgi-nginx-flask:python3.6
docker save -o ./jupyter-datascience-notebook.tar jupyter/datascience-notebook
```

and.. remove other container & image cant' make enough space..

```
Error response from daemon: write /mnt/sda1/var/lib/docker/tmp/docker-export-809037937/d49f83e22c52d598460451c81a14375bb0798faac56135bd5763243ef5a3393c/layer.tar: no space left on device
```

after `docker system prune -a` I got 7gb

```
/dev/sda1                17.9G      6.8G     10.1G  40% /mnt/sda1/var/lib/docker
``` 

and try build jupyter-notebok only.

```
docker-compose build
```

http://home.zany.kr:9003/board/bView.asp?bCode=13&aCode=14131&cBlock=0&cPageNo=1&sType=0&sString=

**Comment by baram204** [comment]
`docker-machine rm default`

manual remove `user/.docker/machine/machines/default`

`docker-machine create --driver virtualbox --virtualbox-disk-size "100000" default`

**Comment by baram204** [comment]
docker save -o ./jupyter-datascience-notebook.tar jupyter/datascience-notebook
... yes issues done.
