### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte

### ISSUE THREAD

**Issue by baram204** [baram204/Used-Car-Price-Expectation-with-ML#7]
```
> python.exe -m flask run
 * Serving Flask app "app.app"
 * Forcing debug mode on
 * Restarting with stat
C:\Users\baram204\Anaconda3\envs\usedcar\lib\runpy.py:125: RuntimeWarning: 'flask.cli' found in sys.modules after import of package 'flask', but prior to execution of 'flask.cli'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
 * Debugger is active!
 * Debugger PIN: 123-960-161
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\site-packages\werkzeug\serving.py", line 774, in inner
    fd=fd)
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\site-packages\werkzeug\serving.py", line 666, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\site-packages\werkzeug\serving.py", line 577, in __init__
    self.address_family), handler)
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Users\baram204\Anaconda3\envs\usedcar\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte
```

**Comment by baram204** [comment]
works
